### ISSUE TITLE
Submit to Carpentries Incubator

### ISSUE THREAD

**Issue by jezcope** [carpentries-incubator/task-management#37]
I checked over the requirements for [Carpentries Incubator](https://carpentries-incubator.org/) lessons and they are more minimal than I expected. I'm happy to go ahead and submit it unless there are any objections? I suspect @olexandr-konovalov will need to sign off on it since the repo is currently under his account.

Looks like we submit by creating an issue with [the lesson proposal template](https://github.com/carpentries-incubator/proposals/issues/new?assignees=tobyhodges&labels=proposal&projects=&template=lesson_proposal.yml&title=%5BProposal%5D%3A+) and wait for Toby to review it.

Any thoughts or comments? Or just 👍🏻 to indicate you're happy 😁

**Comment by olexandr-konovalov** [comment]
@jezcope yes, please go ahead and submit! I an migrate the repository myself as soon as we will get an approval.

**Comment by jezcope** [comment]
Done! https://github.com/carpentries-incubator/proposals/issues/188

I'll leave this issue open to track until the process is complete.

- [x] Submit proposal
- [x] Respond to questions (if any)
- [x] Get approval
- [x] Transfer repository

**Comment by jezcope** [comment]
All complete, thanks to @tobyhodges and @olexandr-konovalov
